// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1f1Cgqb8v3AHyTPtfQzivcx_J1LQfQK8',
    appId: '1:187654504767:web:020b5ed6ce0b4fa4c1138a',
    messagingSenderId: '187654504767',
    projectId: 'blind-clone-622c6',
    authDomain: 'blind-clone-622c6.firebaseapp.com',
    databaseURL: 'https://blind-clone-622c6-default-rtdb.firebaseio.com',
    storageBucket: 'blind-clone-622c6.firebasestorage.app',
    measurementId: 'G-8PT3PSSLGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYN5KWuGIag71a0kkVLz-60ydM7-Cs84o',
    appId: '1:187654504767:android:18c7d027ddb21825c1138a',
    messagingSenderId: '187654504767',
    projectId: 'blind-clone-622c6',
    databaseURL: 'https://blind-clone-622c6-default-rtdb.firebaseio.com',
    storageBucket: 'blind-clone-622c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0Wm3eZbyEQJFwAfvvNJZa7hyBk3V1_E',
    appId: '1:187654504767:ios:3c27538201b0db35c1138a',
    messagingSenderId: '187654504767',
    projectId: 'blind-clone-622c6',
    databaseURL: 'https://blind-clone-622c6-default-rtdb.firebaseio.com',
    storageBucket: 'blind-clone-622c6.firebasestorage.app',
    iosBundleId: 'com.example.blindCloneFlutter',
  );
}
